"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-SelfProtocol',
 'project_name': 'Private Human Gate',
 'track': 'SelfProtocol',
 'pitch': 'A privacy-preserving human verification layer that must approve high-impact '
          'agent actions before any treasury or exchange workflow is planned.',
 'idea_titles': ['ZK Human Check for Treasury Actions',
                 'Privacy-Preserving Operator Approval',
                 'Consent-Bound Agent Identity'],
 'architecture_summary': 'This repo places privacy-preserving human verification in '
                         'front of high-impact agent actions. A guard contract records '
                         'proof attestations and policy windows, while Python '
                         'middleware ensures no treasury or exchange action is planned '
                         'without a valid identity check.',
 'overlap_targets': ['Venice Private Agents',
                     'MetaMask Delegations',
                     'ENS',
                     'Lido stETH Treasury',
                     'Uniswap Agentic Finance',
                     'Status L2'],
 'primary_contract_name': 'SelfGateRegistry',
 'primary_python_module': 'self_gate',
 'category': 'identity',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'identity_state',
                       'description': 'Names, wallets, manifests, and verification '
                                      'proofs.'},
                      {'name': 'permissions',
                       'description': 'Which principals can act on which rails.'},
                      {'name': 'reputation_events',
                       'description': 'Receipts, scores, and attestation updates.'},
                      {'name': 'receipts',
                       'description': 'Submission notes and public evidence links.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for SelfGateRegistry.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'self_gate.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'SelfProtocol',
               'docs_url': 'https://docs.self.xyz/',
               'env_vars': ['SELF_PROTOCOL_API_KEY', 'SELF_VERIFICATION_URL'],
               'endpoint_env': 'SELF_VERIFICATION_URL',
               'action_kind': 'rest_json',
               'purpose': 'Gate sensitive actions behind privacy-preserving proofs.'},
              {'name': 'Venice',
               'docs_url': 'https://docs.venice.ai/',
               'env_vars': ['VENICE_API_KEY',
                            'VENICE_CHAT_COMPLETIONS_URL',
                            'VENICE_MODEL'],
               'endpoint_env': 'VENICE_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Run private reasoning over sensitive inputs.'},
              {'name': 'MetaMask Delegations',
               'docs_url': 'https://docs.metamask.io/delegation-toolkit/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Enforce delegation scopes, expiries, and intent envelopes.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Lido',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Route staking yield through guarded treasury actions.'},
              {'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'Status L2',
               'docs_url': 'https://status.app/',
               'env_vars': ['STATUS_RPC_URL', 'STATUS_RELAYER_URL'],
               'endpoint_env': 'STATUS_RELAYER_URL',
               'action_kind': 'rest_json',
               'purpose': 'Prepare gasless relay bundles for Status L2.'}],
 'actions': [{'id': 'selfprotocol_zk_verify',
              'target': 'selfprotocol',
              'purpose': 'Use SelfProtocol for a bounded action in this repo.',
              'partner': 'SelfProtocol',
              'action_kind': 'rest_json',
              'max_amount_usd': 3,
              'priority': 100,
              'sensitivity': 'high',
              'notes': ['Call SelfProtocol only after a dry-run artifact exists.',
                        'Use https://docs.self.xyz/ for credential setup.']},
             {'id': 'venice_private_analysis',
              'target': 'venice',
              'purpose': 'Use Venice for a bounded action in this repo.',
              'partner': 'Venice',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 95,
              'sensitivity': 'high',
              'notes': ['Call Venice only after a dry-run artifact exists.',
                        'Use https://docs.venice.ai/ for credential setup.']},
             {'id': 'metamask_delegations_delegate_scope',
              'target': 'metamask_delegations',
              'purpose': 'Use MetaMask Delegations for a bounded action in this repo.',
              'partner': 'MetaMask Delegations',
              'action_kind': 'contract_call',
              'max_amount_usd': 2,
              'priority': 90,
              'sensitivity': 'high',
              'notes': ['Call MetaMask Delegations only after a dry-run artifact '
                        'exists.',
                        'Use https://docs.metamask.io/delegation-toolkit/ for '
                        'credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 85,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'lido_yield_route',
              'target': 'lido',
              'purpose': 'Use Lido for a bounded action in this repo.',
              'partner': 'Lido',
              'action_kind': 'contract_call',
              'max_amount_usd': 200,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call Lido only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']},
             {'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'status_l2_gasless_bundle',
              'target': 'status_l2',
              'purpose': 'Use Status L2 for a bounded action in this repo.',
              'partner': 'Status L2',
              'action_kind': 'rest_json',
              'max_amount_usd': 8,
              'priority': 70,
              'sensitivity': 'medium',
              'notes': ['Call Status L2 only after a dry-run artifact exists.',
                        'Use https://status.app/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
